In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
#mimic the behavior of a regular user and reduce the chances of being blocked or banned. 
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
}

# this is first page were we extract content

In [3]:
url='https://www.amazon.in/s?k=mobiles+under+30000+5g+phones&crid=1GO94AW64J84A&sprefix=mobiles+%2Caps%2C354&ref=nb_sb_ss_ts-doa-p_5_8'

In [4]:
r=requests.get(url,headers=headers)

In [5]:
r

In [6]:
soup=BeautifulSoup(r.text,'html.parser')

In [7]:
product_name=soup.find_all('a',attrs={'class':"a-link-normal s-line-clamp-2 s-link-style a-text-normal"})

In [8]:
product_name

[<a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/sspa/click?ie=UTF8&amp;spc=MTo3MTQ3ODQ3MDY1MzM4Njk6MTc0MjY2OTkxMDpzcF9hdGY6MzAwMjYwODM5NDE4MDMyOjowOjo&amp;url=%2FOnePlus-Obsidian-Midnight-256GB-Storage%2Fdp%2FB0D7VKMLGD%2Fref%3Dsr_1_1_sspa%3Fcrid%3D1GO94AW64J84A%26dib%3DeyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos%26dib_tag%3Dse%26keywords%3Dmobiles%2Bunder%2B30000%2B5g%2Bphones%26qid%3D1742669909%26sprefix%3Dmobiles%2B%252Caps%252C354%26sr%3D8-1-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGY%26psc%3D1" target="_blank"><h2 aria-label="Sponsored Ad - OnePlus Nord 4 5G (Obsidian Midnight, 8GB RAM, 256GB Storage)" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>OnePlus Nord 4 5G (Obsidian Midnight, 8GB RAM, 256GB Storage)</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/sspa/click?ie=UTF8&amp;spc=MTo3MTQ3ODQ3MDY1MzM4Njk6MTc0MjY2OTkxMDpzcF9hdGY6MzAwMTU2NTM1NzkxMTMyOjowOjo&amp;url=%2FOneplus-Nord-Chrome-256GB-Storage%2Fdp%2FB0CX5BZXLF%2Fref%3Dsr_1_2_sspa%3Fcrid%3D1GO94AW64J84A%26dib%3DeyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos%26dib_tag%3Dse%26keywords%3Dmobiles%2Bunder%2B30000%2B5g%2Bphones%26qid%3D1742669909%26sprefix%3Dmobiles%2B%252Caps%252C354%26sr%3D8-2-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9hdGY%26psc%3D1" target="_blank"><h2 aria-label="Sponsored Ad - OnePlus Nord CE4 (Dark Chrome, 8GB RAM, 256GB Storage)" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>OnePlus Nord CE4 (Dark Chrome, 8GB RAM, 256GB Storage)</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/iQOO-Snapdragon-Processor-Slimmest-Smartphone/dp/B0DW48MM7C/ref=sr_1_3?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-3" target="_blank"><h2 aria-label="iQOO Neo 10R 5G (Raging Blue, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>iQOO Neo 10R 5G (Raging Blue, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/iQOO-Moonknight-Snapdragon-Processor-Smartphone/dp/B0DW47JCHW/ref=sr_1_4?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-4" target="_blank"><h2 aria-label="iQOO Neo 10R 5G (Moonknight Titanium, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>iQOO Neo 10R 5G (Moonknight Titanium, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/iQOO-Moonknight-Snapdragon-Processor-Smartphone/dp/B0DW478NDF/ref=sr_1_5?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-5" target="_blank"><h2 aria-label="iQOO Neo 10R 5G (Moonknight Titanium, 8GB RAM, 128GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>iQOO Neo 10R 5G (Moonknight Titanium, 8GB RAM, 128GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/Nothing-Storage-Snapdragon-Charging-Expansion/dp/B0DZNP6L5B/ref=sr_1_6?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-6" target="_blank"><h2 aria-label="Nothing Phone (3A) 5G (Black, 8GB RAM, 256GB Storage) | Snapdragon 7s Gen 3 | 50MP+50MP+8MP Cameras | 32MP Front | 6.77” 120Hz AMOLED | 5000mAh Battery | 50W Fast Charging | Up to 16GB RAM Expansion" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>Nothing Phone (3A) 5G (Black, 8GB RAM, 256GB Storage) | Snapdragon 7s Gen 3 | 50MP+50MP+8MP Cameras | 32MP Front | 6.77” 120Hz AMOLED | 5000mAh Battery | 50W Fast Charging | Up to 16GB RAM Expansion</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/Midnight-Toughest-Featured-SUPERVOOC-Additional/dp/B0D53M1ZQX/ref=sr_1_7?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-7" target="_blank"><h2 aria-label='OPPO F27 Pro+ 5G (Midnight Navy, 8GB RAM, 256GB Storage) | 6.7" FHD+ AMOLED Toughest 3D Curved Display|64MP AI Featured Camera|IP69 | 67W SUPERVOOC| with No Cost EMI/Additional Exchange Offers' class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>OPPO F27 Pro+ 5G (Midnight Navy, 8GB RAM, 256GB Storage) | 6.7" FHD+ AMOLED Toughest 3D Curved Display|64MP AI Featured Camera|IP69 | 67W SUPERVOOC| with No Cost EMI/Additional Exchange Offers</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/Oppo-Reno-Pro-Sunset-Gold/dp/B0D9C5JZCT/ref=sr_1_8?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-8" target="_blank"><h2 aria-label="Oppo Reno 12 Pro 5G (Sunset Gold, 256 GB) (12 GB RAM)" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>Oppo Reno 12 Pro 5G (Sunset Gold, 256 GB) (12 GB RAM)</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/realme-Storage-Flagship-Chipset-Brightest/dp/B0D3J7HS89/ref=sr_1_9?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-9" target="_blank"><h2 aria-label="realme GT 6T 5G (Razor Green,8GB RAM+256GB Storage) | India's 1st 7+ Gen 3 Flagship Chipset | 1.5M + AnTuTu Score | 5500mAh+120W | The World's Brightest Flagship Display" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>realme GT 6T 5G (Razor Green,8GB RAM+256GB Storage) | India's 1st 7+ Gen 3 Flagship Chipset | 1.5M + AnTuTu Score | 5500mAh+120W | The World's Brightest Flagship Display</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/Phantom-Purple-Storage-Additional-Exchange/dp/B07WJTMDHX/ref=sr_1_10?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-10" target="_blank"><h2 aria-label="Vivo Y300 5G (Phantom Purple, 8GB RAM, 256GB Storage) with No Cost EMI/Additional Exchange Offers" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>Vivo Y300 5G (Phantom Purple, 8GB RAM, 256GB Storage) with No Cost EMI/Additional Exchange Offers</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/sspa/click?ie=UTF8&amp;spc=MTo3MTQ3ODQ3MDY1MzM4Njk6MTc0MjY2OTkxMDpzcF9tdGY6MzAwNDgwMDc4ODc4MTMyOjowOjo&amp;url=%2FiQOO-Snapdragon-Processor-Supercomputing-Flagship%2Fdp%2FB07WGPJ82V%2Fref%3Dsr_1_11_sspa%3Fcrid%3D1GO94AW64J84A%26dib%3DeyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos%26dib_tag%3Dse%26keywords%3Dmobiles%2Bunder%2B30000%2B5g%2Bphones%26qid%3D1742669909%26sprefix%3Dmobiles%2B%252Caps%252C354%26sr%3D8-11-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1" target="_blank"><h2 aria-label="Sponsored Ad - iQOO Neo9 Pro 5G (Fiery Red, 8GB RAM, 128GB Storage) | Snapdragon 8 Gen 2 Processor | Supercomputing Chip Q1 | Flagship Level Sony IMX920 Camera" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>iQOO Neo9 Pro 5G (Fiery Red, 8GB RAM, 128GB Storage) | Snapdragon 8 Gen 2 Processor | Supercomputing Chip Q1 | Flagship Level Sony IMX920 Camera</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/sspa/click?ie=UTF8&amp;spc=MTo3MTQ3ODQ3MDY1MzM4Njk6MTc0MjY2OTkxMDpzcF9tdGY6MzAwNDYwNTAwOTA5OTMyOjowOjo&amp;url=%2FOnePlus-13R-Smarter-Storage-Nebula%2Fdp%2FB0DPS62DYH%2Fref%3Dsr_1_12_sspa%3Fcrid%3D1GO94AW64J84A%26dib%3DeyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos%26dib_tag%3Dse%26keywords%3Dmobiles%2Bunder%2B30000%2B5g%2Bphones%26qid%3D1742669909%26sprefix%3Dmobiles%2B%252Caps%252C354%26sr%3D8-12-spons%26sp_csd%3Dd2lkZ2V0TmFtZT1zcF9tdGY%26psc%3D1" target="_blank"><h2 aria-label="Sponsored Ad - OnePlus 13R | Smarter with OnePlus AI (12GB RAM, 256GB Storage Nebula Noir)" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>OnePlus 13R | Smarter with OnePlus AI (12GB RAM, 256GB Storage Nebula Noir)</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/Motorola-Fusion-Marshmallow-256GB-Storage/dp/B0D4JLSGBB/ref=sr_1_13?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-13" target="_blank"><h2 aria-label="Motorola Edge 50 Fusion 5G (Marshmallow Blue, 12GB RAM, 256GB Storage)" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>Motorola Edge 50 Fusion 5G (Marshmallow Blue, 12GB RAM, 256GB Storage)</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/T3-Pro-Snapdragon-Processor-Nano-SIM/dp/B0DNK85GFL/ref=sr_1_14?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-14" target="_blank"><h2 aria-label="vivo T3 Pro 5G (Emerald Green, 8GB RAM+ 256GB Storage) | Snapdragon 7 Gen 3 Processor | 120Hz AMOLED Display | Dual Nano-SIM | 5500mAh Battery" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>vivo T3 Pro 5G (Emerald Green, 8GB RAM+ 256GB Storage) | Snapdragon 7 Gen 3 Processor | 120Hz AMOLED Display | Dual Nano-SIM | 5500mAh Battery</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/Samsung-Awesome-Iceblue-Storage-Nightography/dp/B0CWPF945W/ref=sr_1_15?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-15" target="_blank"><h2 aria-label="Samsung Galaxy A35 5G (Awesome Iceblue, 8GB RAM, 256GB Storage) | Premium Glass Back | 50 MP Main Camera (OIS) | Nightography | IP67 | Corning Gorilla Glass Victus+ | sAMOLED with Vision Booster" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>Samsung Galaxy A35 5G (Awesome Iceblue, 8GB RAM, 256GB Storage) | Premium Glass Back | 50 MP Main Camera (OIS) | Nightography | IP67 | Corning Gorilla Glass Victus+ | sAMOLED with Vision Booster</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/Motorola-Fusion-Forest-256GB-Storage/dp/B0D4JM8B2Q/ref=sr_1_16?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-16" target="_blank"><h2 aria-label="Motorola Edge 50 Fusion 5G (Forest Blue, 12GB RAM, 256GB Storage)" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>Motorola Edge 50 Fusion 5G (Forest Blue, 12GB RAM, 256GB Storage)</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/iQOO-Storage-Ultra-Thin-Dimesity-Processor/dp/B07WHS35V6/ref=sr_1_17?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-17" target="_blank"><h2 aria-label="iQOO Z9s 5G (Onyx Green, 8GB RAM, 256GB Storage) | 120 Hz 3D Curved AMOLED Display | 5500 mAh Ultra-Thin Battery | Dimesity 7300 5G Processor | Sony IMX882 OIS Camera with Aura Light" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>iQOO Z9s 5G (Onyx Green, 8GB RAM, 256GB Storage) | 120 Hz 3D Curved AMOLED Display | 5500 mAh Ultra-Thin Battery | Dimesity 7300 5G Processor | Sony IMX882 OIS Camera with Aura Light</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/iQOO-Storage-Snapdragon-Processor-Brightness/dp/B07WHR9ZJ9/ref=sr_1_18?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-18" target="_blank"><h2 aria-label="iQOO Z9s Pro 5G (Luxe Marble, 8Gb Ram, 128Gb Storage) | Snapdragon 7 Gen 3 Processor |120 Hz Curved Amoled Display with 4500 Nits Local Peak Brightness | 5500 Mah Battery | Ai Erase, White" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>iQOO Z9s Pro 5G (Luxe Marble, 8Gb Ram, 128Gb Storage) | Snapdragon 7 Gen 3 Processor |120 Hz Curved Amoled Display with 4500 Nits Local Peak Brightness | 5500 Mah Battery | Ai Erase, White</span></h2></a>,
 <a class="a-link-normal s-line-clamp-2 s-link-style a-text-normal" href="/Redmi-Note-14-5G-Dimensity/dp/B0DPFVDFT3/ref=sr_1_19?crid=1GO94AW64J84A&amp;dib=eyJ2IjoiMSJ9.0AJrL0YBJ_27ur3u-akGA4Vd7Et2l0nNsPxtgO6qm9pVjfT8KNULSWJc6e2aXnl20JcKXxJVtYT_oxAAKMkck0FMQU65Dj5B8X0w261mb190CHWqWcRy_5UA9B3fEYuyYlNZYDz-1QUtqFvEDVkZTp1KkoSIe4vAcNPfsfklvr27X5rNoksYH1FUvJeYNWDS9gCwZybiRjPgo_QHHQltFfEN1Swc6wGtwKH0qwT8G7U.bfrXSHKACOdd6gQK6ERwJB09mnzZiFOA_vxmheWGOos&amp;dib_tag=se&amp;keywords=mobiles+under+30000+5g+phones&amp;qid=1742669909&amp;sprefix=mobiles+%2Caps%2C354&amp;sr=8-19" target="_blank"><h2 aria-label="Redmi Note 14 5G (Titan Black, 8GB RAM 256GB Storage) | Global Debut MTK Dimensity 7025 Ultra | 2100 nits Segment Brightest 120Hz AMOLED | 50MP Sony LYT 600 OIS+EIS Triple Camera" class="a-size-medium a-spacing-none a-color-base a-text-normal"><span>Redmi Note 14 5G (Titan Black, 8GB RAM 256GB Storage) | Global Debut MTK Dimensity 7025 Ultra | 2100 nits Segment Brightest 120Hz AMOLED | 50MP Sony LYT 600 OIS+EIS Triple Camera</span></h2></a>,

In [9]:
mob=[]

In [10]:
for i in product_name:
    name=i.text
    mob.append(name)

In [11]:
mob

['OnePlus Nord 4 5G (Obsidian Midnight, 8GB RAM, 256GB Storage)',
 'OnePlus Nord CE4 (Dark Chrome, 8GB RAM, 256GB Storage)',
 "iQOO Neo 10R 5G (Raging Blue, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours",
 "iQOO Neo 10R 5G (Moonknight Titanium, 8GB RAM, 256GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours",
 "iQOO Neo 10R 5G (Moonknight Titanium, 8GB RAM, 128GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours",
 'Nothing Phone (3A) 5G (Black, 8GB RAM, 256GB Storage) | Snapdragon 7s Gen 3 | 50MP+50MP+8MP Cameras | 32MP Front | 6.77” 120Hz AMOLED | 5000mAh Battery | 50W Fast Charging | Up to 16GB RAM Expansion',
 'OPPO F27 Pro+ 5G (Midnight Navy, 8GB RAM, 256GB Storage) | 6.7" FHD+ AMOLED Toughest 3D Curved Display|64MP AI Featured Camera|IP69 | 67W SUPERVOOC| with No Cost EMI/Additional Exchange Offers',
 'Oppo Reno 12 Pro 5G (Sunset Gold, 256 GB) (12 GB RAM)',
 "realme GT 6T 5G (Razor Green,8GB RAM+256GB Storage) | India's 1st 7+ Gen 3 Flagship Chipset | 1.5M + AnTuTu Score | 5500mAh+120W | The World's Brightest Flagship Display",
 'Vivo Y300 5G (Phantom Purple, 8GB RAM, 256GB Storage) with No Cost EMI/Additional Exchange Offers',
 'iQOO Neo9 Pro 5G (Fiery Red, 8GB RAM, 128GB Storage) | Snapdragon 8 Gen 2 Processor | Supercomputing Chip Q1 | Flagship Level Sony IMX920 Camera',
 'OnePlus 13R | Smarter with OnePlus AI (12GB RAM, 256GB Storage Nebula Noir)',
 'Motorola Edge 50 Fusion 5G (Marshmallow Blue, 12GB RAM, 256GB Storage)',
 'vivo T3 Pro 5G (Emerald Green, 8GB RAM+ 256GB Storage) | Snapdragon 7 Gen 3 Processor | 120Hz AMOLED Display | Dual Nano-SIM | 5500mAh Battery',
 'Samsung Galaxy A35 5G (Awesome Iceblue, 8GB RAM, 256GB Storage) | Premium Glass Back | 50 MP Main Camera (OIS) | Nightography | IP67 | Corning Gorilla Glass Victus+ | sAMOLED with Vision Booster',
 'Motorola Edge 50 Fusion 5G (Forest Blue, 12GB RAM, 256GB Storage)',
 'iQOO Z9s 5G (Onyx Green, 8GB RAM, 256GB Storage) | 120 Hz 3D Curved AMOLED Display | 5500 mAh Ultra-Thin Battery | Dimesity 7300 5G Processor | Sony IMX882 OIS Camera with Aura Light',
 'iQOO Z9s Pro 5G (Luxe Marble, 8Gb Ram, 128Gb Storage) | Snapdragon 7 Gen 3 Processor |120 Hz Curved Amoled Display with 4500 Nits Local Peak Brightness | 5500 Mah Battery | Ai Erase, White',
 'Redmi Note 14 5G (Titan Black, 8GB RAM 256GB Storage) | Global Debut MTK Dimensity 7025 Ultra | 2100 nits Segment Brightest 120Hz AMOLED | 50MP Sony LYT 600 OIS+EIS Triple Camera',
 'Samsung Galaxy M35 5G (Thunder Grey,8GB RAM,256GB Storage)| Corning Gorilla Glass Victus+| AnTuTu Score 595K+ | Vapour Cooling Chamber | 6000mAh Battery | 120Hz Super AMOLED Display| Without Charger',
 "iQOO Neo 10R 5G (Raging Blue, 12GB RAM, 256GB Storage) | Snapdragon 8s Gen 3 Processor | India's Slimmest 6400mAh Battery Smartphone | Segment's Most Stable 90FPS for 5 Hours",
 'Samsung Galaxy A36 5G (Awesome Lavender, 8GB, 256GB) | Awesome Intelligence - AI Smartphone: Circle to Search, My Filter, Object Eraser | 4nm Snapdragon Processor | Flagship Grade Selfie Camera']

In [12]:
df=pd.DataFrame({'mobile_brand':mob})

# here we do extraction from mulitple pages using for loop

In [13]:
mob=[]
for i in range(2,30):
    url='https://www.amazon.in/s?k=mobiles+under+30000+5g+phones&page=2&xpid=C8HXckAWrg5qE&crid=1GO94AW64J84A&qid=1742317149&sprefix=mobiles+%2Caps%2C354&ref=sr_pg_'+str(i)
    r=requests.get(url,headers=headers)
    soup=BeautifulSoup(r.text,'html.parser')
    product_name=soup.find_all('a',attrs={'class':"a-link-normal s-line-clamp-2 s-link-style a-text-normal"})
   
    for j in product_name:
        name=j.text
        mob.append(name)
df=pd.DataFrame({'mobile_brand':mob})

In [14]:
df[['brand','series']]=df['mobile_brand'].str.split(' ',n=1,expand=True)

In [15]:
df.drop('mobile_brand',axis=1,inplace=True)

In [16]:
df['series']=df['series'].str.split('(').str[0]

In [17]:
df['mobile']='smart_mobile'

In [18]:
df

       brand                          series        mobile
0    OnePlus                      Nord 4 5G   smart_mobile
1       iQOO                     Neo 10R 5G   smart_mobile
2      HONOR                         200 5G   smart_mobile
3    Samsung                  Galaxy M35 5G   smart_mobile
4       iQOO                         Z9x 5G   smart_mobile
..       ...                             ...           ...
611     iQOO                         Z9s 5G   smart_mobile
612     iQOO                     Z9 Lite 5G   smart_mobile
613     Vivo                        Y300 5G   smart_mobile
614  OnePlus  13R | Smarter with OnePlus AI   smart_mobile
615  OnePlus   13 | Smarter with OnePlus AI   smart_mobile

[616 rows x 3 columns]

In [19]:
df=df[['mobile','brand','series']]

In [114]:
df

           mobile     brand              series
0    smart_mobile     Redmi         Note 14 5G
1    smart_mobile      Oppo      Reno10 Pro 5G
2    smart_mobile   Samsung      Galaxy A35 5G
3    smart_mobile   Nothing              Phone
4    smart_mobile      Oppo     Reno 12 Pro 5G
..            ...       ...                 ...
443  smart_mobile      iQOO             Z9s 5G
444  smart_mobile   Samsung      Galaxy M35 5G
445  smart_mobile  Motorola  Edge 50 Fusion 5G
446  smart_mobile      iQOO         Neo 10R 5G
447  smart_mobile      iQOO         Z9 Lite 5G

[448 rows x 3 columns]